CREATE TABLE IF NOT EXISTS genre (
    genre_id        int PRIMARY KEY,
    name            varchar(20) not null
);

CREATE TABLE IF NOT EXISTS users (
    id              int generated by default as identity primary key,
    email           varchar(50) not null,
    login           varchar(20) not null,
    name            varchar(50),
    birthday        date not null
);

CREATE TABLE IF NOT EXISTS films (
    id              int generated by default as identity primary key,
    name            varchar(100) not null,
    description     varchar(200) not null,
    release_date    date not null,
    duration        int not null,
    rating          varchar(5) not null,
    genre_id        int not null,
    CONSTRAINT fk_genre
        FOREIGN KEY (genre_id)
            REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS mutual_friendship (
    user_id         int,
    friend_id       int,
    status          varchar(10) not null,
    CONSTRAINT fk_user_friendship
        FOREIGN KEY (user_id)
            REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id         int not null,
    user_id         int not null,
    CONSTRAINT fk_film_like
        FOREIGN KEY (film_id)
            REFERENCES films(id),
    CONSTRAINT fk_user_like
        FOREIGN KEY (user_id)
            REFERENCES users(id)
);

--DELETE FROM users WHERE id = 'dolore';